version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
  groups:
    minor-and-patch-version-updates:
      update-types:
        - minor
        - patch
  ignore:
  - dependency-name: minitest
    versions:
    - 5.14.4
